/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Workout = {
  _id: string;
  _type: "workout";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  userId?: string;
  date?: string;
  duration?: number;
  exercises?: Array<{
    exercise?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "exercises";
    };
    sets?: Array<{
      reps?: number;
      weight?: number;
      _type: "exerciseSet";
      _key: string;
    }>;
    _type: "workoutExercise";
    _key: string;
  }>;
};

export type Exercises = {
  _id: string;
  _type: "exercises";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  instruction?: string;
  muscleGroup?: string;
  difficulty?: "post-op" | "control" | "intermediate" | "advanced" | "athletic";
  videoUrl?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Workout | Exercises | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../src/app/(app)/(tabs)/active-workout.tsx
// Variable: findExerciseQuery
// Query: *[_type == "exercises" && name == $name][0]{  _id,  name,}
export type FindExerciseQueryResult = {
  _id: string;
  name: string | null;
} | null;

// Source: ../src/app/(app)/(tabs)/exercises.tsx
// Variable: exercisesQuery
// Query: *[_type == "exercises"]{  ...}
export type ExercisesQueryResult = Array<{
  _id: string;
  _type: "exercises";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  instruction?: string;
  muscleGroup?: string;
  difficulty?: "advanced" | "athletic" | "control" | "intermediate" | "post-op";
  videoUrl?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
}>;

// Source: ../src/app/(app)/(tabs)/history/index.tsx
// Variable: getWorkoutsQuery
// Query: *[_type == "workout" && userId == $userId] | order(date desc){    _id,    date,    duration,    exercises[] {      exercise-> {        _id,        name      },      sets[]{        reps,        weight,        weightunit,        _type,        _key      },      _type,      _key    }  }
export type GetWorkoutsQueryResult = Array<{
  _id: string;
  date: string | null;
  duration: number | null;
  exercises: Array<{
    exercise: {
      _id: string;
      name: string | null;
    } | null;
    sets: Array<{
      reps: number | null;
      weight: number | null;
      weightunit: null;
      _type: "exerciseSet";
      _key: string;
    }> | null;
    _type: "workoutExercise";
    _key: string;
  }> | null;
}>;

// Source: ../src/app/(app)/(tabs)/history/workout-record.tsx
// Variable: getWorkoutRecordQuery
// Query: *[_type == "workout" && _id == $workoutId][0]{  _id,  date,  duration,  exercises[] {    exercise-> {      _id,      name  },  sets[]{    reps,    weight,    weightunit,    _type,    _key  },  _type,  _key  }}
export type GetWorkoutRecordQueryResult = {
  _id: string;
  date: string | null;
  duration: number | null;
  exercises: Array<{
    exercise: {
      _id: string;
      name: string | null;
    } | null;
    sets: Array<{
      reps: number | null;
      weight: number | null;
      weightunit: null;
      _type: "exerciseSet";
      _key: string;
    }> | null;
    _type: "workoutExercise";
    _key: string;
  }> | null;
} | null;

// Source: ../src/app/(app)/exercise-details.tsx
// Variable: singleExerciseQuery
// Query: *[_type == "exercises" && _id == $id][0]
export type SingleExerciseQueryResult = {
  _id: string;
  _type: "exercises";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  instruction?: string;
  muscleGroup?: string;
  difficulty?: "advanced" | "athletic" | "control" | "intermediate" | "post-op";
  videoUrl?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"exercises\" && name == $name][0]{\n  _id,\n  name,\n}": FindExerciseQueryResult;
    "*[_type == \"exercises\"]{\n  ...\n}": ExercisesQueryResult;
    "*[_type == \"workout\" && userId == $userId] | order(date desc){\n    _id,\n    date,\n    duration,\n    exercises[] {\n      exercise-> {\n        _id,\n        name\n      },\n      sets[]{\n        reps,\n        weight,\n        weightunit,\n        _type,\n        _key\n      },\n      _type,\n      _key\n    }\n  }": GetWorkoutsQueryResult;
    "*[_type == \"workout\" && _id == $workoutId][0]{  _id,  date,  duration,  exercises[] {    exercise-> {      _id,      name  },  sets[]{    reps,    weight,    weightunit,    _type,    _key  },  _type,  _key  }}": GetWorkoutRecordQueryResult;
    "*[_type == \"exercises\" && _id == $id][0]": SingleExerciseQueryResult;
  }
}
